language: cpp
compiler:
    - clang
notifications:
    email: true
env:
    matrix: 
        - JULIAVERSION="juliareleases" 
        - JULIAVERSION="julianightlies" 
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
    - sudo apt-get update -qq -y
    - sudo apt-get install libpcre3-dev julia -y
    - git config --global user.name "Leah Hanson"
    - git config --global user.email "leah.a.hanson@gmail.com"
    - git submodule update --init --recursive
script:
    - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("WebSockets"))`); Pkg.pin("WebSockets"); Pkg.resolve()'
    - julia -e 'using WebSockets; @assert isdefined(:WebSockets); @assert typeof(WebSockets) === Module'
    - julia test/tests.jl

