language: cpp
compiler:
    - clang
notifications:
    email: true
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/julianightlies -y
    - sudo apt-get update -qq -y
    - sudo apt-get install libpcre3-dev julia -y
    - git config --global user.name "Leah Hanson"
    - git config --global user.email "leah.a.hanson@gmail.com"
    - git submodule update --init --recursive
script:
    - julia -e "Pkg.init()"
    - mkdir -p ~/.julia/WebSockets
    - cp -R ./* ~/.julia/WebSockets/
    - julia -e 'Pkg.resolve()'
    - julia ~/.julia/WebSockets/test/tests.jl

