language: julia
os:
    - linux
    - osx
julia:
    - 0.3
    - 0.4
    - nightly
sudo: false
notifications:
    email: false
after_success:
    - julia -e 'cd(Pkg.dir("WebSockets")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
